FROM registry.redhat.io/ubi8/ubi

RUN dnf -y install http://download.lab.bos.redhat.com/rcm-guest/puddles/OpenStack/rhos-release/rhos-release-latest.noarch.rpm
RUN rhos-release 16 -p z1 --without-ceph
RUN dnf -y install python3-tripleoclient
RUN dnf -y install sudo
RUN dnf -y install patch
RUN dnf -y install python3-osc-placement
RUN dnf -y clean all
ADD hostnamectl /usr/local/bin/
