apiVersion: controlplane.openstack.org/v1beta1
kind: ControlPlane
metadata:
  name: openstack-ctlplane
  namespace: openstack
spec:
  glance:
    replicas: 1
  keystone:
    replicas: 1
  placement:
    replicas: 1
  cinder:
    cinderAPIReplicas: 1
    cinderSchedulerReplicas: 1
    cinderBackupReplicas: 1
    cinderVolumeReplicas: 1
  nova:
    novaAPIReplicas: 1
    novaSchedulerReplicas: 1
    novaConductorReplicas: 1
    novaMetadataReplicas: 1
    novaNoVNCProxyReplicas: 1
  storage_class: host-nfs-storageclass
