#!/bin/bash

# Usage: cluster-join <cluster id> <remote raft address> [<remote raft address> ...]
# 
# If <cluster id> is exactly "any" we will join any cluster we find at the given address

set -ex -o pipefail

. /env.sh

cid=$1; shift || exit 1
[ $# -gt 0 ] || exit 1

[ -f "$db" ] && exit 0

[ $cid != "any" ] && cid_arg="--cid=$cid"
exec ovsdb-tool join-cluster $cid_arg "$db" "$db_name" "$raft_address" "$*"
