#!/bin/bash

set -e -o pipefail

. /env.sh

cid=$(ovsdb-tool db-cid "$db")
name=$(ovsdb-tool db-name "$db")
sid=$(ovsdb-tool db-sid "$db")
raft_address=$(ovsdb-tool db-local-address "$db")
db_address="tcp:${SERVER_NAME}:${db_port}"

jq -n --arg cid "$cid" \
      --arg name "$name" \
      --arg sid "$sid" \
      --arg raft_address "$raft_address" \
      --arg db_address "$db_address" \
      '{"clusterID": $cid, "name": $name, "serverID": $sid,
        "raftAddress": $raft_address, "dbAddress": $db_address}'
