apiVersion: v1
kind: ConfigMap
metadata:
  name: cinder-volume1-config-data-custom
  namespace: openstack
data:
  cinder.conf: |
    [DEFAULT]
    enabled_backends = nfs
    [nfs]
    backend_host=hostgroup
    volume_backend_name=nfs
    volume_driver=cinder.volume.drivers.nfs.NfsDriver
    nfs_shares_config=/etc/cinder/nfs_shares
  nfs_shares: |
    # nfs shares
    192.168.111.1:/home/nfs/cinder
